### PR TITLE
Fixed #2

### LINKED ISSUE #2: SSL error
SSL error on morph but not on local
```
/app/vendor/bundle/ruby/1.9.1/gems/net-http-persistent-2.5.2/lib/net/http/persistent/ssl_reuse.rb:70:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
 	from /app/vendor/bundle/ruby/1.9.1/gems/net-http-persistent-2.5.2/lib/net/http/persistent/ssl_reuse.rb:70:in `block in connect'
 	from /app/vendor/ruby-1.9.3/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
 	from /app/vendor/ruby-1.9.3/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
 	from /app/vendor/bundle/ruby/1.9.1/gems/net-http-persistent-2.5.2/lib/net/http/persistent/ssl_reuse.rb:70:in `connect'
 	from /app/vendor/ruby-1.9.3/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
 	from /app/vendor/ruby-1.9.3/lib/ruby/1.9.1/net/http.rb:751:in `start'
 	from /app/vendor/bundle/ruby/1.9.1/gems/net-http-persistent-2.5.2/lib/net/http/persistent.rb:508:in `connection_for'
 	from /app/vendor/bundle/ruby/1.9.1/gems/net-http-persistent-2.5.2/lib/net/http/persistent.rb:788:in `request'
 	from /app/vendor/bundle/ruby/1.9.1/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:258:in `fetch'
 	from /app/vendor/bundle/ruby/1.9.1/gems/mechanize-2.5.1/lib/mechanize.rb:407:in `get'
 	from /app/planningalerts_xml_feed/planningalerts_xml_feed.rb:8:in `scrape'
 	from scraper.rb:3:in `<main>'
```

### PR DESCRIPTION
**Pull request by LoveMyData**
Fixed #2 

planningalerts_xml_feed module is no longer working with new SSL cert, no clue on how to change 'submodule', hence, updated main scraper to restore services

### CODE REVIEW

**Comment by henare** [comment]
@LoveMyData this PR effectively forks [`planningalerts_xml_feed`](https://github.com/planningalerts-scrapers/planningalerts_xml_feed/blob/f55e3a83862e11805832b5ce06fa966eb15cc570/planningalerts_xml_feed.rb) which means the changes we make aren't shared across the other scrapers that might use this module. For this reason I think it would be better if you made these improvements to that upstream module instead.

I'll assign this back to you to consider that suggestion and make the change if you agree.

**Comment by LoveMyData** [comment]
@henare, if we really want to fix the upstream, we need to regularly update the cert file in openssl (I think ruby use that).

This scraper's code to disable SSL check is bad habit. The root cause is the cert I believes. I am not too sure how the back end works.

It ran ok on my local and not on morph. https://github.com/openaustralia/morph/issues/939

**Comment by henare** [comment]
>This scraper's code to disable SSL check is bad habit.

Yep, I totally agree :+1: How about we add another parameter to the `.scrape` method in the upstream module that optionally allows you to disable the SSL check when you're using it with a broken site?

**Comment by LoveMyData** [comment]
@equivalentideas Another thought... can you rename the existing data.sqlite file to something else like archive.sqlite and morph can handle multiple database files

**Comment by LoveMyData** [comment]
fixes #2, #3 as the entire scraper has been rewritten

**Pull request merged**
